name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - run: make build
      - run: make lint
      - run:  make test

  ci-windows-lib:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'
      - uses: pnpm/action-setup@v4
        with:
          version: '10.31.0'
      - run: pnpm install --frozen-lockfile --config.dedupe-peer-dependents=false
        working-directory: lib
      - run: |
          'node -e "require(''node:fs'').rmSync(''dist'', { recursive: true, force: true })"'
          pnpm exec tsc --outDir dist
          pnpm exec jest --verbose
        working-directory: lib
